### ISSUE TITLE
Sass Eyeglass support?

### ISSUE THREAD

**Issue by philwareham** [LukyVj/family.scss#28]
Would you consider adding Eyeglass support (https://github.com/sass-eyeglass/eyeglass)? It's more intuitive that just installing via vanilla NPM (where users would then have to specify a direct import path to the stylesheet within Sass).

**Comment by LukyVj** [comment]
Hi @philwareham ! Thanks for the suggestion! 
It's definitely a good idea!  I didn't knew about that until now..

**Comment by LukyVj** [comment]
Will not be on Sass eyeglass for now.

**Comment by EmilEriksen** [comment]
Would also love Eyeglass support. I'm wondering why this was closed?

**Comment by LukyVj** [comment]
It's closed because I currently have no time to keep maintaining this project. 
If you feel like you want to add Eyeglass, please do :) 

I've been watching their docs at the time this issue was opened, I found it unclear. So I never bothered myself looking deeper. 

But once again, if you want Eyeglass support, you can clone the repo and do what it need :) 

Thanks!

**Comment by EmilEriksen** [comment]
I submitted a pull request (#87) that adds Eyeglass support :) I just learned about Eyeglass but hopefully I've avoided making any mistakes although I agree that the Eyeglass docs are confusing.
