### ISSUE TITLE
How about compile to css

### ISSUE THREAD

**Issue by x09326** [LukyVj/family.scss#83]
Hi, I'm trying to host this lib on [cdnjs](https://cdnjs.com).

But cdnjs cannot host scss files.
Could you provide css files?
Thanks.
https://github.com/cdnjs/cdnjs/pull/8652

**Comment by pzi** [comment]
Hey Guan,

Have you read my comment in https://github.com/LukyVj/family.scss/issues/82#issuecomment-248801260 ?

> ...given family.scss has no actual output ...

There is no output and there will never be because it's a [mixin](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#mixins) library. Mixins do not generate any CSS output until they are `@include`d in a Sass file. Even then, the output only makes sense in combination with actual site styles and is therefore _very_ different to a standalone file like normalize.css or sanitize.css.

**Comment by LukyVj** [comment]
Hi, family isn't a css library per say, it's a mixin library. Therefore, if I compile it, there would be no CSS outputed.
